apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: kuard-rs
  name: kuard-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard-rs-pod
  template:
    metadata:
      labels:
        app: kuard-rs-pod
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
        resources:
          requests:
            cpu: 100m
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP



