apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    rc: kubia-rc
  name: kubia-rc
spec:
  replicas: 2
  selector:
    app: kubia-pod
  template:
    metadata:
      labels:
        app: kubia-pod
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080

