apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: database
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    server: 159.65.37.139
    path: /share1

