apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: web
spec:
  containers:
  - image: redis
    name: redis-pod
    stdin: true
    tty: true
    ports:
    - containerPort: 9090
      name: http
      protocol: TCP
